title:              Mibrahim-dev Blog
email:              mrmibrahim3@gmail.com
description:        A blog for documenting learning and projects
author:             Mr M.Ibrahim
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://mibrahim-dev.github.io"

# Social Profiles
twitter_username:   mrmibrahim3
github_username:    mibrahim-dev
facebook_username:  mibrahim-dev
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
